dist: xenial
language: cpp
compiler: gcc
addons:
  apt:
    packages:
      - libboost-test-dev
      - libspdlog-dev
      - libgtest-dev
script:
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package