name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_NUMBER: ${{github.run_number}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: sudo apt install -y cmake libspdlog-dev libboost-test-dev libgtest-dev
      - name: Prepare
        run: cmake .
      - name: Build
        run: cmake --build .
      - name: Test
        run: cmake --build . --target test
      - name: Pack
        run: cmake --build . --target package
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          path: packages
